# Generated by Django 3.2.11 on 2022-09-04 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coordinates', '0002_rename_coordinate_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
